### ISSUE TITLE
AsyncPath using synchronous Path.walk

### ISSUE THREAD

**Issue by Fisch37** [alexdelorenzo/aiopath#33]
The `AsyncPath.walk` method does not return an `AsyncGenerator` as expected, but instead a synchronous `Generator` object. This appears to be because of `.walk` not being defined in `AsyncPath` and thus the method from `Path` is used instead.

## Expected Behaviour
`AsyncPath.walk` should return an `AsyncGenerator` object that can be used in `async for` statements and implements `__aiter__` and `__anext__`.

## Actual Behaviour
`AsyncPath.walk` follows the MRO and is really `Path.walk`, thus returning a normal generator. Using it in `async for` will cause a TypeError.
```py
>>> async for p in AsyncPath(".").walk():
...     print(p)
... 
Traceback (most recent call last):
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
TypeError: 'async for' requires an object with __aiter__ method, got generator
```

## Steps to reproduce
1. Install `aiopath`
2. In a console, IDLE, or some program of your choice that runs python enter the following:
```py
from aiopath import AsyncPath
print(*AsyncPath(".").walk())
```
3. See that there was an output instead of the error that should have occured.

**Comment by SerGeRybakov** [comment]
@alexdelorenzo Shall we expect any updates on this in the nearest future or you'd prefer a PR?
